require("dotenv").config();

const { ethers } = require("ethers");

const RPC_URL =
    process.env.BLOCKCHAIN_RPC_URL;

const CONTRACT_ADDRESS =
    process.env.BLOCKCHAIN_CONTRACT_ADDRESS;

const PRIVATE_KEY =
    process.env.BLOCKCHAIN_ADMIN_PRIVATE_KEY;

if (!RPC_URL) {
    throw new Error(
        "BLOCKCHAIN_RPC_URL is missing in .env"
    );
}

if (!CONTRACT_ADDRESS) {
    throw new Error(
        "BLOCKCHAIN_CONTRACT_ADDRESS is missing in .env"
    );
}

if (!PRIVATE_KEY) {
    throw new Error(
        "BLOCKCHAIN_ADMIN_PRIVATE_KEY is missing in .env"
    );
}

// Provider
const provider =
    new ethers.JsonRpcProvider(RPC_URL);

// Wallet
const wallet =
    new ethers.Wallet(
        PRIVATE_KEY,
        provider
    );

// Nonce manager
const adminsigner = wallet;
   // new ethers.NonceManager(wallet);

// Load the exact ABI generated by Hardhat
const artifact =
    require("./blockchain/GovernmentFundABI.json");

// Contract
const contract =
    new ethers.Contract(
        CONTRACT_ADDRESS,
        artifact.abi,
        adminsigner
    );

console.log(
    "Blockchain contract connected:",
    CONTRACT_ADDRESS
);

module.exports = {
    provider,
    wallet,
    adminsigner,
    contract,
    CONTRACT_ADDRESS
};